# Generated by Django 3.0.4 on 2020-03-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=250)),
                ('hobbites', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moadel', models.BigIntegerField()),
                ('shomare_daneshjoi', models.BigIntegerField()),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.human')),
            ],
        ),
    ]
