# Generated by Django 3.0.4 on 2020-03-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='student',
        ),
    ]
