# Generated by Django 3.0.4 on 2020-03-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20200329_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dars',
            field=models.CharField(default='dars', max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='zarfiat',
            field=models.BigIntegerField(default=30),
        ),
    ]
